### ISSUE TITLE
"Run Extension" logs "Error is  h: request to http://65.1.61.75:8080/intro failed, reason: connect ETIMEDOUT 65.1.61.75:8080"

### ISSUE THREAD

**Issue by mark-wiemer** [mark-wiemer-org/ahkpp#464]
Can't figure out what's causing this :(

```
Error is  h: request to http://65.1.61.75:8080/intro failed, reason: connect ETIMEDOUT 65.1.61.75:8080
    at ClientRequest.<anonymous> (c:\Users\markw\.vscode\extensions\circlecodesolution.ccs-flutter-color-1.2.5\dist\extension.js:2:85360)
    at ClientRequest.emit (C:\Users\markw\repos\ahkpp\lib\events.js:531:35)
    at Socket.socketErrorListener (C:\Users\markw\repos\ahkpp\lib\_http_client.js:500:9)
    at Socket.emit (C:\Users\markw\repos\ahkpp\lib\events.js:519:28)
    at emitErrorNT (C:\Users\markw\repos\ahkpp\lib\internal\streams\destroy.js:169:8)
    at emitErrorCloseNT (C:\Users\markw\repos\ahkpp\lib\internal\streams\destroy.js:128:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {type: 'system', errno: 'ETIMEDOUT', code: 'ETIMEDOUT', erroredSysCall: 'connect', stack: 'h: request to http://65.1.61.75:8080/intro fa…ons (node:internal/process/task_queues:82:21)', …}
```

**Comment by mark-wiemer** [comment]
Seems to be an extension host issue, I see this on other repos as well, not unique to this one
